<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ArisuBot.Core\ArisuBot.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="1.6.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
